# Site settings
title: Yu Liu
subtitle: ""
name: "Yu Liu"
email: yu-y.liu@polyu.edu.hk
description: >- 
  Assistant Professor at Hong Kong Polytechnic University
url: "https://yuliu3.github.io"
repository: "yuliu3/yuliu3.github.io"

# Site Author
author:
  name: "Yu Liu"
  avatar: "images/yuliu3.jpg"
  bio: "Assistant Professor, Department of Computing, Hong Kong Polytechnic University"
  location: "Kowloon, HK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yu-y.liu@polyu.edu.hk"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "YOUR_RESEARCHGATE_URL"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "YOUR_LINKEDIN_URL"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "YOUR_GITHUB_URL"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "YOUR_GOOGLE_SCHOLAR_URL"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "YOUR_ORCID_URL"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "YOUR_GITHUB_URL"
    - label: "Feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true